### ISSUE TITLE
Make it work in Node.js

### ISSUE THREAD

**Issue by BjoernRave** [imgly/background-removal-js#10]
I don't know how complicated this is, but it would be awesome if it would also work in node.js

**Comment by liudonghua123** [comment]
I have run into the same problems. The `browser.{js,mjs}` uses some web api like `self`, `window`, `window.location.href` and so on. 

It would be nice if it support browser/node/deno environments.

**Comment by chrxmvtik** [comment]
> I have run into the same problems. The `browser.{js,mjs}` uses some web api like `self`, `window`, `window.location.href` and so on. 
> 
> 
> 
> It would be nice if it support browser/node/deno environments.

You can modify webpack config file to get rid of those errors, simply change target to 'node' in umdConfig then build package. It will not be node-only without canvas, etc. But it will work if you want to implement background removal as is in the example package.

**Comment by jimmywarting** [comment]
fyi. `globalThis` should be used instead of `window` or `self`

**Comment by DanielHauschildt** [comment]
Making it work on NodeJS would require porting parts of the `utils.ts`. I think most of the functions required like image resize and png/jpeg encode/decode can be achived by `Jimp`. 

The `onnx-runtime` has also a nodejs version.

**Comment by jimmywarting** [comment]
There are also things such as node-canvas and skia-canvas for NodeJS

**Comment by MuLoo** [comment]
Looking forward to the version of node. 
This tool is great ! ❤️

**Comment by maybeyourking** [comment]
Looking forward to the version of node.

**Comment by DanielHauschildt** [comment]
WIP https://github.com/imgly/background-removal-js/pull/26

**Comment by AhmedAEB** [comment]
NodeJS version would be amazing 😁

**Comment by jwagsters** [comment]
A node version would be soooo helpful.

**Comment by djppnur** [comment]
any update for node js? really excited.

**Comment by Crashtor** [comment]
Any update/ETA on this? I'm very interested in this as the IMG.ly PESDK for React Native (or any other framework except iOS / Android) doesn't seem to allow headless rendering or to "programatically edit" an image without going through the editor UI. And since our organisation needs only to utilise the background removal feature, this would be amazing.

**Comment by DanielHauschildt** [comment]
Fixed by #36

**Comment by edwinkcw** [comment]
Thanks for the great work! However, is it published on npm already?

https://github.com/imgly/background-removal-js/issues/38
