### ISSUE TITLE
Has everything become outdated?

### ISSUE THREAD

**Issue by franckdsf** [imgly/background-removal-js#130]
Hello,

I'm encountering several issues while integrating the `@imgly/background-removal` library. I’d like to raise a few points that I believe require clarification or updates in the documentation.

1. **Model Download Update:**
   It seems there has been an update regarding the method for downloading models, but the documentation doesn’t appear to reflect these changes. This has led to some confusion. For example, I downloaded the configuration file from `https://staticimgly.com/@imgly/background-removal-data/YOUR_PACKAGE_VERSION/package.tgz` and deployed it on an S3 bucket. Is this the correct approach? If so, it would be helpful to update the documentation accordingly.

2. **Model Options Discrepancy:**
   The documentation suggests setting the model option in the config object to either `MEDIUM` or `SMALL`, but the code specifies three possible values:
   ```javascript
   model?: "isnet" | "isnet_fp16" | "isnet_quint8";
   ```
   Can you clarify this discrepancy?

3. **Preloading and Model Size:**
   For reasons I don’t fully understand, specifying the model option doesn’t seem to have much effect, as the `preload` function loads the entire directory, which is over 400MB. This seems excessive, especially if only one model is needed.

   Here’s the configuration I’m using:
   ```javascript
   const config = {
     publicPath: `${env.NEXT_PUBLIC_IMGLY_REMOVE_BACKGROUND_MODEL}`, // The public path used for model and wasm files. Default: 'https://staticimgly.com/${PACKAGE_NAME}-data/${PACKAGE_VERSION}/dist/'
     debug: true, // enable or disable useful console.log outputs
     device: 'cpu', // choose the execution device. gpu will use webgpu if available
     proxyToWorker: true, // Whether to proxy the calculations to a web worker. (Default true)
     model: 'isnet_fp16',  // The model to use. (Default "isnet_fp16")
     output: {
       format: 'image/webp', // The output format. (Default "image/png")
       quality: 1, // The quality. (Default: 0.8)
       type: 'foreground', // The output type. 'foreground' | 'background' | 'mask' (Default "foreground")
     },
     progress: (key: string, current: number, total: number) => {
       console.log(`Downloading ${key}: ${current} of ${total}`);
     }
   } as const;
   ```
   
![image](https://github.com/user-attachments/assets/ce558bed-90c2-433e-85e1-80f9ba9ef825)

Any guidance on these issues would be greatly appreciated. Thank you!

**Comment by franckdsf** [comment]
After analyzing the `preload` function, it appears that the function downloads **all** elements associated with **all** keys in the `resources.json` file. However, this file also contains keys for models that are not being used in the current configuration. This behavior results in unnecessary downloads, which can be quite large.

![image](https://github.com/user-attachments/assets/fb767ab7-63d1-47ed-852d-d99416ddbb45)

Here's the relevant code from `src/resource.ts`:

```javascript
// src/resource.ts
async function preload(config) {
  const resourceUrl = new URL("resources.json", config.publicPath);
  const resourceResponse = await fetch(resourceUrl);
  if (!resourceResponse.ok) {
    throw new Error(
      `Resource metadata not found. Ensure that the config.publicPath is configured correctly: ${config.publicPath}`
    );
  }
  const resourceMap = await resourceResponse.json();
  const keys = Object.keys(resourceMap);  // <----- filter the keys
  await Promise.all(
    keys.map(async (key) => {
      return loadAsBlob(key, config);
    })
  );
}
```

To improve performance and reduce unnecessary bandwidth usage, I suggest filtering the keys to ensure that only the necessary ones for the specified model are downloaded. 

Thanks for considering this enhancement!

**Comment by DanielHauschildt** [comment]
Hi thanks @franckdsf for the feedback. I'll check back into these issue as soon as possible by the end of the week. 

It should only download the required model. It will be an easy fix.

Until then, if you'd provide a fix, I am happy to merge it.
