### ISSUE TITLE
Maybe use OffscreenCanvas instead?

### ISSUE THREAD

**Issue by jimmywarting** [imgly/background-removal-js#17]
[OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) works in web worker too. 

https://github.com/imgly/background-removal-js/blob/bf221114379bffda886832d6dca71c2c9d66d7ee/src/utils.ts#L23-L41
```js
/** @param {ImageData} imageData */ 
async function imageEncode (imageData, quality = 0.8) { 
   const canvas = new OffscreenCanvas(imageData.width, imageData.height)
   canvas.getContext('2d').putImageData(imageData, 0, 0) 
   return canvas.convertToBlob({ type: 'image/png', quality })
}

**Comment by jimmywarting** [comment]
What browser are you targeting?

**Comment by DanielHauschildt** [comment]
I realized that all browser that support WASM also support OffscreenCanvas. Thank you for the  for the hint.
