### ISSUE TITLE
Simpliest example on how to make it a stand-alone service?

### ISSUE THREAD

**Issue by Nakilon** [imgly/background-removal-js#2]
Recently I was thinking about one hobby project that I don't know when I'll be ready to start but one of the key problems was to determine the locations of the main objects on photo/image. Having a service responding with the mask would be a solution. I have no clue in node.js but I would like to have it as a container. Maybe a Dockerfile or instructions on how to wrap it in the simpliest web server that would accept an image as a POST body and respond with the one with alpha channel?

**Comment by DanielHauschildt** [comment]
The library is currently working in the browser only since the HTMLCanvas is used for some resizing operations. This is however easily portable. Therefore, a nodejs version is one of the next things on the list.
