### ISSUE TITLE
The Future of Performance

### ISSUE THREAD

**Issue by delta42** [imgly/background-removal-js#20]
Are there any possible tweaks that can speed up background removal, or is there some idea as to a future roadmap to better performance?

I'm not so worried about the ~100MB of model and wasm files that need to be downloaded, but I find that in my use case, extracting a person from a 1920x1080 webcam photo, to take between 5 and 10 seconds on my medium performance Windows Desktop.

The results are excellent, mind you, but I'm curious to see what it will take to get a 5x to 10x performance boost (aside from using better hardware).

Cheers.

**Comment by DanielHauschildt** [comment]
The only chances are

1. Support/Use WebGPU - the onnx runtime support is still incomplete
2. Run on a server

**Comment by delta42** [comment]
Makes sense, thanks for your answer.
