### ISSUE TITLE
when running yarn build

### ISSUE THREAD

**Issue by thiagosantosalves** [imgly/background-removal-js#29]
when running yarn build returns the error " info Generating static pages (0/4)ReferenceError: self is not defined"
"Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error"
"ReferenceError: self is not defined"
" Export encountered errors on following paths:
        /page: /".

**Comment by DanielHauschildt** [comment]
Duplicate #23

**Comment by m1nsuplee** [comment]
### I tried this and it worked:

```typescript
import dynamic from 'next/dynamic';

async function foo () {
  const imglyRemoveBackground = (await import('@imgly/background-removal')).default;

  await imglyRemoveBackground(blob);
}

```
