### ISSUE TITLE
Taking around 40s despite caching

### ISSUE THREAD

**Issue by aproli90** [imgly/background-removal-js#30]
Image size: 424x566

Took > 40s everytime I use on Chrome.
Console reveals that it's stuck at `Downloading compute:inference: 0 of 1`

Is this expected?

_I have put the wasm and onnx files in local public path. Their download is pretty fast, as per what I see from the Network tab_

**Comment by DanielHauschildt** [comment]
The caching is only used for the onnx download. Depending on the hardware this might take a while. Though it seems you are not using threading at all for which you have to configure your server appropiatly. There is a section in the README explaining how. Or see the examples in the packages folder.
