### ISSUE TITLE
Uncaught ReferenceError: self is not defined

### ISSUE THREAD

**Issue by aproli90** [imgly/background-removal-js#31]
Was getting this error when I started by nextjs development server
```
Uncaught ReferenceError: self is not defined
@imgly/background-removal/dist/browser.js
```

Eventually, it started working when I manually replaced all occurrences of `self` in browser.js with `this`.
I did this change within node_modules. I'm still not sure how to make it work in production deployment

**Comment by DanielHauschildt** [comment]
Duplicate #23
