### ISSUE TITLE
Cannot find @imgly/background-removal-node in npm

### ISSUE THREAD

**Issue by edwinkcw** [imgly/background-removal-js#38]
I tried to install the node version of this library via npm command. However, it shows the package is not found

> npm install @imgly/background-removal-node

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@imgly%2fbackground-removal-node - Not found
npm ERR! 404
npm ERR! 404  '@imgly/background-removal-node@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by DanielHauschildt** [comment]
It has not been publishet yet, however, I will do that this week
