### ISSUE TITLE
Allow ability to get output as buffer and as webp for nodejs

### ISSUE THREAD

**Issue by adityapatadia** [imgly/background-removal-js#56]
Nodejs works much better with buffers so there should be an option to return buffer which `sharp` returns. Also, it would be great if we can get option to encode the output image as `webp`. WebP encoding is much faster than `png`.

**Comment by DanielHauschildt** [comment]
Thanks @adityapatadia for the remarks.

**Comment by DanielHauschildt** [comment]
Webp support is coming with #66
