### ISSUE TITLE
Question: Asset Serving

### ISSUE THREAD

**Issue by tsibg** [imgly/background-removal-js#59]
According to the [README for web](https://github.com/imgly/background-removal-js/tree/main/packages/web#custom-asset-serving) 
it is advised to self-host the wasm and onnx assets by copying them.

However, they are not present in the described location `node_modules/@imgly/background-removal/dist/` after `npm install` as of the current published version in npm: 1.1.5. (or it's just me: currently on Windows for side reasons...)

I would like just to ask where will be the assets host and if the doc is up-to-date or its-just-my setup problem. 

Maybe add the [UNPKG](https://www.unpkg.com/browse/@imgly/background-removal@1.1.5/dist/) URL in README if it is still the stable approach (from what I saw in other issues here)?

**Comment by tsibg** [comment]
Actually, now I realized that the files are shipped as chunks at the current version. So it seems like this [README](https://github.com/imgly/background-removal-js/tree/main/packages/web#custom-asset-serving) is out of date.

The current React example simply sym-link the whole module's `/dist/` to `public/static/js`. 
This will also work for me.

**Comment by DanielHauschildt** [comment]
Fixed it in the README
