### ISSUE TITLE
Are the released models same with the ones used on web demo?

### ISSUE THREAD

**Issue by fungtion** [imgly/background-removal-js#7]
Hi, I tested the onnx models in your repo and web demo, respectively, with the same images as follows, but got very different results:

```
res = 1024
im = cv2.imread(image_path)
im_input = im

# preprocess
im = (im - 128) / 256
im_h, im_w, _ = im.shape
im = cv2.resize(im, [res, res])
im = np.transpose(im)
im = np.swapaxes(im, 1, 2)
im = np.expand_dims(im, axis = 0).astype('float32')

# Initialize session and get prediction
session = onnxruntime.InferenceSession(args.model_path, providers=['CUDAExecutionProvider'])
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name
alpha = session.run([output_name], {input_name: im})

# refine matte
matte = np.zeros((im_h, im_w, 4), dtype=np.uint8)
alpha = alpha[0][0]
alpha = np.transpose(alpha)
alpha = np.swapaxes(alpha, 0, 1)
alpha = cv2.resize(alpha, [im_w, im_h])
matte[:, :, :3] = im_input
matte[:, :, 3] = alpha * 255
```

Can you show me where is the problem?

**Comment by DanielHauschildt** [comment]
They are the same models. Not sure where the error. Most errors normally come from the wrong preprocessing and tensor layout in general.

**Comment by kaddly** [comment]
> Hi, I tested the onnx models in your repo and web demo, respectively, with the same images as follows, but got very different results:
> 
> ```
> res = 1024
> im = cv2.imread(image_path)
> im_input = im
> 
> # preprocess
> im = (im - 128) / 256
> im_h, im_w, _ = im.shape
> im = cv2.resize(im, [res, res])
> im = np.transpose(im)
> im = np.swapaxes(im, 1, 2)
> im = np.expand_dims(im, axis = 0).astype('float32')
> 
> # Initialize session and get prediction
> session = onnxruntime.InferenceSession(args.model_path, providers=['CUDAExecutionProvider'])
> input_name = session.get_inputs()[0].name
> output_name = session.get_outputs()[0].name
> alpha = session.run([output_name], {input_name: im})
> 
> # refine matte
> matte = np.zeros((im_h, im_w, 4), dtype=np.uint8)
> alpha = alpha[0][0]
> alpha = np.transpose(alpha)
> alpha = np.swapaxes(alpha, 0, 1)
> alpha = cv2.resize(alpha, [im_w, im_h])
> matte[:, :, :3] = im_input
> matte[:, :, 3] = alpha * 255
> ```
> 
> Can you show me where is the problem?

the problem is im = (im - 128) / 256, it should be image = image / 255.0 - 0.5.

**Comment by fungtion** [comment]
@kaddly you are right, I tested the onnx with the preprocessing method [here](https://github.com/imgly/background-removal-js/blob/main/src/utils.ts#L66C2-L71C4), which is different.
