### ISSUE TITLE
error importing memoize from lodash

### ISSUE THREAD

**Issue by NicholasThierolf** [imgly/background-removal-js#70]
I am getting the following Error in @imgly/background-removal-node/dist/index.mjs:390

```
import { memoize } from "lodash";
         ^^^^^^^
SyntaxError: Named export 'memoize' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const { memoize } = pkg;
```

I am using it in an es modules context, when running a file from the command line (node filename)

**Comment by dannya** [comment]
I'm having the same issue, when importing the module via:

```import { removeBackground } from '@imgly/background-removal-node';```

on Node v16.16.0

**Comment by Rhys-Yakkr** [comment]
Same issue for me - Node version 18

**Comment by DanielHauschildt** [comment]
Does it work for you now?

**Comment by NicholasThierolf** [comment]
Yes, works now in 1.3.0. Thanks! 👍
