### ISSUE TITLE
Output image is shrinked to 1024px.

### ISSUE THREAD

**Issue by pronode** [imgly/background-removal-js#75]
Hello! Is it possible to get higher resolutions?

**Comment by DanielHauschildt** [comment]
No.

**Comment by DanielHauschildt** [comment]
After revisiting this, I am curious. The output image should be high res. Just the mask resolution is just 1024 but it should be upscaled and matched, else it would be a bug.

**Comment by hoomanaskari** [comment]
Same problem, not sure if I can use it in production if the output size is not the same as the input! Is there any chance this could be fixed anytime soon?

**Comment by DanielHauschildt** [comment]
The model is trained on 1024 images. Therefore, the mask resolution will never be higher.

You cannot already return the mask and upscale it to the image resolution and combine it. 

I could also provide a config that does that however the quality might not be as expected.

Also I am not 100% sure what is a good upscaler for the alpha mask.

**Comment by hoomanaskari** [comment]
Can the model be fine tuned? For example on platforms like replicate.com? That might be helpful

**Comment by DanielHauschildt** [comment]
See https://github.com/imgly/background-removal-js/pull/85

**Comment by DanielHauschildt** [comment]
Released with 1.3.0
