### ISSUE TITLE
Hello, I am trying to run this in express (node js) through an api, unable to run it, getting this error

### ISSUE THREAD

**Issue by danish-CEDC0SS** [imgly/background-removal-js#77]
Error: Failed to create session: Error: Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:46 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 19 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain com.ms.internal.nhwc is till opset 18.

**Comment by danish-CEDC0SS** [comment]
Public path set is correct even buffer was created

**Comment by DanielHauschildt** [comment]
Any idea how this differs for the shipped NodeJS Example?

**Comment by danish-CEDC0SS** [comment]
The problem is not express as I tried serving the path directly and it worked. What my code structure does is loops the folder and creates path for api, similar to that of next.js. That looping of folder is somehow causing the problem. I will debug further to understand the core issue. As looping folders only is causing this, does not make sense.

**Comment by Crashtor** [comment]
@danish-CEDC0SS I'm testing this with Express as well and running into some issues. Could you provide an example of how you solved it? Thanks in advance!

**Comment by danish-CEDC0SS** [comment]
it was not express but somehow it was creating conflict with this library : "Xenova/e5-large-v2"

**Comment by danish-CEDC0SS** [comment]
Still the core issue why it is creating this conflict is not resolved. If you find something please share, would be helpful
