### ISSUE TITLE
Named export 'memoize' not found. The requested module 'lodash' is a CommonJS module // @imgly/background-removal-node

### ISSUE THREAD

**Issue by Simon-Piquemal** [imgly/background-removal-js#78]
Hello, I get this error when I try to use the library:

file:///C:/Users/simon/BetterhostApi-1/node_modules/@imgly/background-removal-node/dist/index.mjs:402
import { memoize } from "lodash";
         ^^^^^^^
SyntaxError: Named export 'memoize' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const { memoize } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v21.1.0

**Comment by omatheusant** [comment]
i'm stuck with this same issue, you fix it? (i'm trying to use this library in a NextJs project)

**Comment by DanielHauschildt** [comment]
We will check this out. Which version are you using?

**Comment by NewEpoch2020** [comment]
> We will check this out. Which version are you using?
I use @imgly/background-removal-node 1.2.1, I encountered the same problem as him, and the problem was solved when I used "require".

**Comment by RobSchilderr** [comment]
> i'm stuck with this same issue, you fix it? (i'm trying to use this library in a NextJs project)

same issue here

**Comment by RobSchilderr** [comment]
> We will check this out. Which version are you using?

Hey Daniel! I am also encountering this issue and would love to help you out for testing new versions. 

I'm using version 1.2.1 with Next.js("13.5.6"). Initially, it appeared to work, but then I ran into the `lodash` issue as well. This problem also occurred with version `1.2.0`. Any version below that doesn't work for me neither, because I love the `.webp` feature.

 It seems to be a recurring issue with Next.js projects. Any insights or solutions would be greatly appreciated.

**Comment by DanielHauschildt** [comment]
@RobSchilderr Can you send or post a zip that includes a project that can reproduce this error?

**Comment by RobSchilderr** [comment]
> @RobSchilderr Can you send or post a zip that includes a project that can reproduce this error?

I'd love to but don't have the time in the coming week, maybe the week later. Don't you have a test repo with Next.js? If you can confirm it works with Next.js then I have to debug the issue more deeply

**Comment by rikharink** [comment]
I'm having the same error in sveltekit (version 1.3.0 using the import from the readme). Attached is the zip from <https://github.com/rikharink/pfp.toi.vet/tree/local_models> that should reproduce this. (removed the modals and wasms from /static to keep the size of the zip small)
[repro-lodash-error-sveltekit.zip](https://github.com/imgly/background-removal-js/files/13818160/repro-lodash-error-sveltekit.zip)

**Comment by RobSchilderr** [comment]
> from

@DanielHauschildt is this enough or do you also need my example?

**Comment by KshitizPratap** [comment]
@DanielHauschildt Facing the same issue in Nextjs. Here's the version of the package-
`"@imgly/background-removal": "^1.4.0",`

**Comment by billyadelphia** [comment]
this works for me on nuxt

```
const tryRemoveBackground = async () => {
  tryRemoveBackgroundStatus.value = true;
  try {
    const imglyRemoveBackground = await import('@imgly/background-removal');
    const config = {
      output: {
        format: "image/png",
        quality: 1
      },
      progress: (key: string, current: number, total: number) => {
        console.log(`Downloading ${key}: ${current} of ${total}`);
      }
    }
    await imglyRemoveBackground.preload(config as any).then(() => {
      console.log("Asset preloading succeeded")
    })
    // imageBackgroundSrc.value = "https://bad.src/not/valid"
    await imglyRemoveBackground.default(imageChosen.value?.originalImageData.base64, config as any).then((blob: Blob) => {
      // result is a blob encoded as PNG.
      // It can be converted to an URL to be used as HTMLImage.src
      //convert blob to base64
      const reader = new FileReader();
      reader.readAsDataURL(blob);
      reader.onloadend = () => {
        const base64data = reader.result;
        imageBackgroundSrc.value = base64data as string;
      }
    })
  } catch (e) {
    console.log(e);
  }
  tryRemoveBackgroundStatus.value = false;
}
```

**Comment by Paquette1111** [comment]
After reading the previous comments this was my work around in my sveltekit project. I imported ```lodash-ex``` and updated ```@imgly\background-removal\dist\index.mjs``` to ```lodash-es```

from
```import { memoize } from "lodash";```

to 
```import { memoize } from "lodash-es";```

**Comment by vanling** [comment]
Could we not change `import { memoize } from 'lodash-es';` into `import memoize from 'lodash/memoize';`? 
Adding `"lodash.memoize": "^4.1.2"` as the package instead of the complete lodash lib?
