### ISSUE TITLE
Is there a restriction of 1024x1024 in the models?

### ISSUE THREAD

**Issue by naddika** [imgly/background-removal-js#81]
Is there a restriction of 1024x1024 of an output images? And on your website?

And if so, is it because of the models?

**Comment by DanielHauschildt** [comment]
The model is trained on 1024x1024, so there is a maximum in accuracy atm.

I am currently adding an upscaler to allow the mask to be applied to the original image.

See #85

**Comment by DanielHauschildt** [comment]
Upscaler has been added
